# Generated by Django 5.1 on 2024-08-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('', 'Escolha um evento'), ('SERESTA', 'Seresta dos Namorados'), ('PAGODE', 'Pagode só Para Amigos'), ('RODEIO', 'Rodeio'), ('CIRCO', 'Circo Fantástico'), ('SHOW', 'Show Taty Girl'), ('APRESENTAÇÃO', 'Show Henrique e Juliano')], default='', max_length=100)),
                ('data_evento', models.DateField()),
                ('horário', models.TimeField()),
                ('local', models.CharField(choices=[('', 'Escolha o Local do Evento a seguir'), ('PRAÇA_DA_IGREJA_MATRIZ', 'Praça da Igreja Matriz'), ('AVENIDA_OSMAR_BASTOS', 'Avenida Osmar Bastos'), ('ESCOLA_EUDES_MAGALHÃES', 'Escola Eudes Magalhães'), ('LOTEAMENTO_ALTA_VISTA', 'Loteamento Alta Vista'), ('PRAÇA_DO_JAURO', 'Praça do Jauro')], default='', max_length=50)),
                ('entrada', models.CharField(choices=[('INTEIRA', 'Inteira'), ('MEIA', 'Meia'), ('GRATUITA', 'Gratuita')], default='INTEIRA', max_length=50)),
                ('quantidade_de_ingressos', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dados_eventos',
            },
        ),
    ]
